#!/usr/bin/env python

HELP_TEXT = """
git-gpg - remote encrypted git repositories.

Usage:

    # Add a remote.
    git gpg add REMOTE_NAME ARCHIVE_PATH

    # Remove a remote.
    git gpg remove REMOTE_NAME

    # Show gpg remotes.
    git gpg show

    # Show details of a gpg remote.
    git gpg show REMOTE_NAME

    # Push to a remote. See `git help push` for options.
    git gpg push [OPTIONS] REMOTE_NAME [REFSPEC]

    # Pull from a remote. See `git help push` for options.
    git gpg pull [OPTIONS] REMOTE_NAME [REFSPEC]

    # Show this screen.
    git gpg help
"""

import glob
import hashlib
import os
import re
import shutil
import subprocess
import sys
import time

def error_and_exit(s):
    print(s)
    exit(-1)

def ensure_path(path):
    if not os.path.exists(path):
        os.makedirs(path)

def delete_path(path):
    if os.path.exists(path):
        shutil.rmtree(path)

def get_staging_path(remote_name):
    return os.path.join(".git", "gpg_remotes", remote_name)

def assert_git_directory():
    """
    Exit with error if we are not in a git repo.
    """
    if not os.path.isdir(".git"):
        error_and_exit("Not in a git repository.")

def assert_remote_exists(remote_name):
    """
    Exit with error if the remote is missing or not configured correctly.
    """
    staging_path = get_staging_path(remote_name)
    if not os.path.exists(staging_path):
        error_and_exit("Missing '%s'." % staging_path)

def assert_remote_unchanged(remote_name):
    """
    Exit with error if the remote repo has been updated since we last pulled changes.
    """
    do_fetch_remote_lock(remote_name)
    if get_config(remote_name, "remote-lock") != get_config(remote_name, "local-lock"):
        error_and_exit("The gpg remote may have changed. Run `git gpg pull %s`" % remote_name)

def get_remote_repo_path(args):
    """
    Return the remote blob path specified on the command line.
    """
    if len(sys.argv) < 2:
        error_and_exit("Must provide a remote blob remote path.")
    return sys.argv[1]

def get_current_git_branch():
    """
    Return the current git branch.
    """
    return subprocess.check_output(["git", "rev-parse", "--abbrev-ref", "HEAD"]).strip()

def set_config(remote_name, key, value):
    new_key = "gpg-remote.%s.%s" % (remote_name, key)
    subprocess.check_call(["git", "config", "--local", new_key, value])

def get_config(remote_name, key):
    new_key = "gpg-remote.%s.%s" % (remote_name, key)
    p = subprocess.Popen(["git", "config", new_key], stdout = subprocess.PIPE)
    p.wait()
    if p.returncode == 0:
        return p.communicate()[0].strip()
    else:
        return None

def unset_config(remote_name, key):
    new_key = "gpg-remote.%s.%s" % (remote_name, key)
    subprocess.call(["git", "config", "--unset", new_key])

def get_user_email():
    return subprocess.check_output(["git", "config", "user.email"]).strip()

def get_remotes_list():
    remotes = []
    try:
        output = subprocess.check_output(["git", "config", "--get-regexp", "gpg-remote.*"])
    except:
        output = ""

    for line in output.split("\n"):
        m = re.match(".*\.(.*)\..* .*", line)
        if m != None:
            remotes.append(m.group(1))
    return sorted(list(set(remotes)))

def generate_lock_value():
    s = get_user_email() + str(time.time()*1000000)
    return hashlib.md5(s).hexdigest()

def rewrite_git_arguments(args):
    """
    Given a list of git arguments, rewrite the arguments to replace the remote
    gpg name with the staging repository path.

    Return (remote_name, new_args).
    """

    # Vars.
    remotes     = get_remotes_list()
    remote_name = None
    args        = list(args)
    new_args    = []

    # Rewrite the pull args to replace remote name with the staging repository path.
    while len(args) > 0:
        arg = args.pop(0)
        if arg in remotes:
            remote_name = arg
            local_repo_path = os.path.join(get_staging_path(remote_name), "git")
            new_args.append(local_repo_path)
        else:
            new_args.append(arg)
    new_args.extend(args)

    # Ensure that we have found a remote name.
    if remote_name == None:
        error_and_exit("Could not find a gpg remote by that name.")

    # Return.
    return (remote_name, new_args)

###
# Commands
###

def do_help():
    print(HELP_TEXT)

def do_show(remote_name = None):
    remotes = get_remotes_list()
    if remote_name == None:
        if len(remotes) > 0:
            print "\n".join(remotes)
        else:
            print "No remotes defined."
    elif not remote_name in remotes:
        print "Remote '%s' not found." % remote_name
    else:
        print "gpg remote %s" % remote_name
        print "- URL: %s" % get_config(remote_name, "url")
        print "- GPG Recipient: %s" % get_config(remote_name, "gpg-recipient")

def do_add(remote_name, remote_repo_path):
    """
    Add an encrypted remote repository.
    """
    assert_git_directory()

    # Assemble some paths.
    path = get_staging_path(remote_name)
    if os.path.exists(path):
        error_and_exit("The remote name '%s' already exists." % remote_name)
    ensure_path(path)

    # Set configuration.
    user_email = get_user_email()
    set_config(remote_name, "url", remote_repo_path)
    set_config(remote_name, "gpg-recipient", user_email)

    print(get_config(remote_name, "url"))

    # Success!
    print("Added gpg remote '%s'." % remote_name)

def do_remove(remote_name):
    """
    Remove an encrypted remote repository."
    """
    assert_git_directory()

    # Remove the files.
    path = get_staging_path(remote_name)
    delete_path(path)

    # Unset configuration.
    unset_config(remote_name, "url")
    unset_config(remote_name, "gpg-recipient")

    # Success!
    print("Removed gpg remote '%s'." % remote_name)

def do_fetch_remote_lock(remote_name):
    """
    Refresh the lock value.
    """

    # Prepare some vars.
    remote_lock_path = get_config(remote_name, "url") + ".lock"
    staging_path     = get_staging_path(remote_name)
    local_lock_path  = os.path.join(staging_path, "remote.gpg") + ".lock"

    # Fetch the remote lock value.
    if subprocess.call(["rsync", remote_lock_path, local_lock_path], stdout = subprocess.PIPE, stderr = subprocess.PIPE) == 0:
        with open(local_lock_path, 'r') as f:
            lock_value = f.read()
        set_config(remote_name, "remote-lock", lock_value)
    else:
        lock = generate_lock_value()
        set_config(remote_name, "local-lock", lock)
        set_config(remote_name, "remote-lock", lock)

def do_push_local_lock(remote_name):
    # Prepare some vars.
    remote_lock_path = get_config(remote_name, "url") + ".lock"
    staging_path     = get_staging_path(remote_name)
    local_lock_path  = os.path.join(staging_path, "remote.gpg") + ".lock"
    lock_value       = get_config(remote_name, "local-lock")

    # Write the lock value.
    with open(local_lock_path, 'w') as f:
        f.write(lock_value)

    # Fetch the remote lock value.
    if subprocess.call(["rsync", local_lock_path, remote_lock_path], stdout = subprocess.PIPE, stderr = subprocess.PIPE) != 0:
        error_and_exit("Could not update the remote lock.")

def do_fetch(remote_name):
    """
    Download the remote blob.
    Decrypt the blob into the staging repository.
    """
    assert_git_directory()
    assert_remote_exists(remote_name)

    # Prepare some vars.
    remote_repo_path = get_config(remote_name, "url")
    staging_path     = get_staging_path(remote_name)
    local_gpg_path   = os.path.join(staging_path, "git.gpg")
    local_repo_path  = os.path.join(staging_path, "git")
    gpg_recipient    = get_config(remote_name, "gpg-recipient")

    # Transfer files from remote.
    print("Fetching files. This may take a second.")
    ensure_path(local_gpg_path)
    if subprocess.call(["rsync", "-am", "--delete", "--delete-excluded", remote_repo_path + "/", local_gpg_path]) != 0:
        # If it didn't work, then initialize a new bare repository.
        subprocess.call(["git", "init", "--bare", local_repo_path])
        print("Initialized new gpg remote '%s'." % remote_name)

    # Delete any files in local_repo_path that don't exist in local_gpg_path.
    paths = []
    ensure_path(local_repo_path)
    for root, dirnames, filenames in os.walk(local_repo_path):
        for file in filenames:
            path = os.path.join(root, file)
            if not os.path.isfile(path.replace(local_repo_path, local_gpg_path) + ".gpg"):
                print("Removing old file %s." % path)
                os.remove(path)

    # Get a list of files to decrypt.
    paths = []
    for root, dirnames, filenames in os.walk(local_gpg_path):
        for filename in filenames:
            path = os.path.join(root, filename)
            output_path = path.replace(local_gpg_path, local_repo_path)[0:-4]

            # Only decrypt .gpg files.
            if not path.endswith(".gpg"):
                continue

            # Don't decrypt an object that already exists.
            if path.find("/objects/") >= 0 and os.path.isfile(output_path):
                # Don't decrypt an object file that already exists.
                continue

            # Add to list of files to decrypt.
            paths.append(path)

    # Decrypt the files.
    if len(paths) > 0:
        print("Decrypting files.")
        if subprocess.call(["gpg", "--decrypt-files", "--quiet", "--recipient", gpg_recipient] + paths) != 0:
            error_and_exit("Could not decrypt '%s'" % path)

    # Move files and clean up times.
    for path in paths:
        # Move file to the correct place.
        output_path = path.replace(local_gpg_path, local_repo_path)[0:-4]
        ensure_path(os.path.dirname(output_path))
        os.rename(path[0:-4], output_path)

        # Fix the modified time.
        time = os.path.getmtime(path)
        os.utime(output_path, (time, time))

    # Extract the "refs.tgz" file.
    refs_path = os.path.join(local_repo_path, "refs.tgz")
    if subprocess.call(["tar", "-zx", "-f", refs_path, "-C", local_repo_path]) != 0:
        # error_and_exit("Could not extract %s" % refs_path)
        print("HERE")

    # Fetch the remote lock and update the local lock.
    do_fetch_remote_lock(remote_name)
    set_config(remote_name, "local-lock", get_config(remote_name, "remote-lock"))

    # Success!
    print("Fetched from gpg remote '%s'." % remote_name)

def do_upload(remote_name):
    """
    Tar, gzip, and encrypt the staging repository.
    Upload to the remote blob.
    """
    assert_git_directory()
    assert_remote_exists(remote_name)

    # Ensure that we know about the latest copy of the blob.
    assert_remote_unchanged(remote_name)

    # Update the lock. We do this first so that if other processes have tried
    # to upload changes, then both of them encounter an error and back off.
    new_lock = generate_lock_value()
    set_config(remote_name, "local-lock", new_lock)
    set_config(remote_name, "remote-lock", new_lock)
    do_push_local_lock(remote_name)

    # Prepare some vars.
    remote_repo_path = get_config(remote_name, "url")
    staging_path     = get_staging_path(remote_name)
    local_gpg_path   = os.path.join(staging_path, "git.gpg")
    local_repo_path  = os.path.join(staging_path, "git")
    gpg_recipient    = get_config(remote_name, "gpg-recipient")

    # Ensure paths.
    ensure_path(local_gpg_path)
    ensure_path(local_repo_path)

    # Delete any files in local_repo_path that don't exist in local_gpg_path.
    for root, dirnames, filenames in os.walk(local_gpg_path):
        for file in filenames:
            path = os.path.join(root, file)
            if not os.path.isfile(path.replace(local_gpg_path, local_repo_path)[0:-4]):
                print("Removing old file %s." % path)
                os.remove(path)

    # Create the "refs.tgz" file.
    refs_path = os.path.join(local_repo_path, "refs.tgz")
    if subprocess.call(["tar", "-c", "-f", refs_path, "-C", local_repo_path, "refs"]) != 0:
        error_and_exit("Could not create %s" % refs_path)

    # Get a list of files to encrypt.
    paths = []
    for root, dirnames, filenames in os.walk(local_repo_path):
        for filename in filenames:
            path = os.path.join(root, filename)
            output_path = path.replace(local_repo_path, local_gpg_path) + ".gpg"

            # Only encrypt actual files.
            if os.path.isdir(path):
                continue

            # Only encrypt files in certain paths.
            if not path.find("/HEAD") >= 0 and \
                not path.find("/refs.tgz") >= 0 and \
                not path.find("/packed-refs") >= 0 and \
                not path.find("/objects/") >= 0:
                continue

            # Don't encrypt already encrypted object files.
            if path.find("/objects/") >= 0 and os.path.exists(output_path):
                continue

            # Add to list for encryption.
            paths.append(path)

    if len(paths) > 0:
        # Encrypt the files.
        print("Encrypting files...")
        if subprocess.call(["gpg", "--batch", "--yes", "--encrypt-files", "--recipient", gpg_recipient] + paths) != 0:
            error_and_exit("Could not encrypt '%s'." % local_repo_path)

        # Move the files and clean up times.
        for path in paths:
            # Move file to the correct place.
            output_path = path.replace(local_repo_path, local_gpg_path) + ".gpg"
            ensure_path(os.path.dirname(output_path))
            os.rename(path + ".gpg", output_path)

            # Update the modification time.
            time = os.path.getmtime(path)
            os.utime(output_path, (time, time))

    # Upload the encrypted files.
    # IMPORTANT: NEVER PUT QUOTES AROUND THE --include OR --exclude FLAGS IN
    # RSYNC. IT WILL CAUSE THE FLAGS TO BE IGNORED.
    print("Uploading files. This may take a second.")
    if subprocess.call([
        "rsync", "-am", "--delete", "--delete-excluded", "--delay-updates",
        "--include=*/", "--include=HEAD.gpg", "--include=packed-refs.gpg", "--include=refs.tgz.gpg", "--include=objects/*/*.gpg", "--exclude=*",
        ".", remote_repo_path], cwd = local_gpg_path) != 0:
        error_and_exit("Could not upload '%s' to '%s'." % (local_repo_path, remote_repo_path))

    # Ensure that we know about the latest copy of the blob.
    assert_remote_unchanged(remote_name)

    # Generate a lock. Set the local and remote lock.
    new_lock = generate_lock_value()
    set_config(remote_name, "remote-lock", new_lock)
    set_config(remote_name, "local-lock", new_lock)
    do_push_local_lock(remote_name)

    # Success!
    print("Uploaded to gpg remote '%s'." % remote_name)

def do_pull(*args):
    """
    Fetch changes from the remote blob into our staging
    repository, then pull them into the local repository.
    """
    assert_git_directory()

    # Process the args.
    remote_name, git_arguments = rewrite_git_arguments(args)

    # Fetch from the remote repo into the staging repository.
    do_fetch(remote_name)

    # Pull from staging repository into our local repository.
    if subprocess.call(["git", "pull"] + git_arguments) == 0:
        print("Pulled from gpg remote '%s'." % remote_name)

def do_push(*args):
    """
    Push changes from the local repository into the staging repository, then
    push them to the remote blob.
    """
    assert_git_directory()

    # Process the args.
    remote_name, git_arguments = rewrite_git_arguments(args)

    # Make sure the remote hasn't changed.
    assert_remote_unchanged(remote_name)

    # Make sure we have a local repo.
    staging_path    = get_staging_path(remote_name)
    local_repo_path = os.path.join(staging_path, "git")
    if not os.path.exists(local_repo_path):
        subprocess.call(["git", "init", "--bare", local_repo_path])
        print("Initialized new gpg remote '%s'." % remote_name)

    # Push from our local repository into the staging repository.
    if subprocess.call(["git", "push"] + git_arguments) == 0:
        do_upload(remote_name)
        print("Pushed to gpg remote '%s'." % remote_name)

###
# Run
###
# Calls do_add, do_remove, do_pull, etc.
script_name = sys.argv.pop(0)
if len(sys.argv) == 0:
    do_show()
else:
    method = "do_" + sys.argv.pop(0)
    if method in locals():
        locals()[method](*sys.argv)
    else:
        print "'%s' is not a valid command. Run 'git gpg help' for help." % method